export enum PositionsEnum {
    FRONTEND_DEVELOPER = 'FRONTEND_DEVELOPER',
	BACKEND_DEVELOPER = 'BACKEND_DEVELOPER',
	QA_ENGINEER = 'QA_ENGINEER',
	UI_UX_DESIGNER = 'UI_UX_DESIGNER',
	DATABASE_DEVELOPER = 'DATABASE_DEVELOPER',
	ANALYST = 'ANALYST'
}